services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
  
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    build: . 
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
   
  phpmyadmin:
    image: phpmyadmin

    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8081:80
      
volumes:
  mysql_data:
